# Generated by Django 5.0.1 on 2024-02-06 17:59

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_search_uuid_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='globalgroup',
            name='uuid_field',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
